[FIX] runbot{,_extend}: force exact dbname for 'run_odoo' job type
We need to force dbname when running odoo, otherwise WorkerCron will
attemps to connect to each available databases and check for compat,
raising many:

bad query: b"SELECT latest_version FROM ir_module_module WHERE name='base'"
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^

..note: WorkerCron does not respect dbfilter has we cannot compute '%d'
  and '%h' maker.

So we instead allow multiple database list so that WorkerCron are only
started on those databases.

For compat with standard we take the last 'install_odoo' databases, and
allow for more 'restore' databases.