[FIX] runbot: fix AttributeError for repo with empty 'addons_path' field.
As 'addons_path' fields is not required, as empty value will be return
as False (bool), this commit fix the error that are raise in such case.

2019-07-30 16:22:49,390 9904 ERROR runbot odoo.addons.runbot.models.build: 00122-10-0-b440db failed running step base: 'bool' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/models/build.py", line 642, in _schedule
    pid = build.active_step._run(build)  # run should be on build?
  File "/home/odoo/runbot/extra/runbot/models/build_config.py", line 176, in _run
    return self._run_step(build, log_path)
  File "/home/odoo/runbot/extra/runbot_extend/models/build_config.py", line 43, in _run_step
    return super(ConfigStep, self)._run_step(build, log_path)
  File "/home/odoo/runbot/extra/runbot/models/build_config.py", line 182, in _run_step
    return self._run_odoo_install(build, log_path)
  File "/home/odoo/runbot/extra/runbot/models/build_config.py", line 282, in _run_odoo_install
    cmd = build._cmd(python_params, py_version)
  File "/home/odoo/runbot/extra/runbot/models/build.py", line 892, in _cmd
    cmd = ['python%s' % py_version] + python_params + [os.path.join(server_dir, server_file), '--addons-path', ",".join(addons_paths)]
  File "/home/odoo/runbot/extra/runbot/models/build.py", line 864, in _get_addons_path
    for addons_path in commit.repo.addons_paths.split(','):
AttributeError: 'bool' object has no attribute 'split'
2019-07-30 16:22:49,392 9904 DEBUG runbot odoo.addons.runbot.models.build: Build 122 run 00122-10-0-b440db failed running step base: